### ISSUE TITLE
refreshing source doesn't work

### ISSUE THREAD

**Issue by xhanrot** [fengyuanchen/completer#2]
Hi,

Here is an example source :

var tabSource = [1, 2, 3],
      $autoCompleteControl = $("#textSearch");

 $autoCompleteControl.completer({
    separator: "",
    source: tabSource
});

tabSource = null;
tabSource = [4, 5, 6];

 $autoCompleteControl.completer({
    separator: "",
    source: tabSource
});

The problem here is that the refresh of completer source with [4, 5, 6] doesn't work : autocomplete still shows choices from [1, 2, 3] array.

**Comment by fengyuanchen** [comment]
If you want to change the source, you should destroy the old instance first:

```js
var tabSource = [1, 2, 3],
    $autoCompleteControl = $("#textSearch");

$autoCompleteControl.completer({
  separator: "",
  source: tabSource
});

$autoCompleteControl.completer('destroy'); // Destroy the existed instance
tabSource = [4, 5, 6];

$autoCompleteControl.completer({
  separator: "",
  source: tabSource
});
```
